"use client";
import { useParams,useRouter } from "next/navigation";
import { useState } from "react";
import { updateBlog } from "@/lib/api/blogs";
import { StudioShell } from "@/components/studio/StudioShell";
import { ImageUpload } from "@/components/studio/ImageUpload";
import { TacticalCard } from "@/components/ui/states";
const field="border border-gold/20 bg-ink p-3 text-white outline-none focus:border-gold/60";
export default function EditBlogPage(){const params=useParams<{id:string}>(),router=useRouter(),[error,setError]=useState<string|null>(null),[saving,setSaving]=useState(false),[body,setBody]=useState(""),[header,setHeader]=useState(""),[photo,setPhoto]=useState("");const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError(null);try{await updateBlog(params.id,{...(header?{title:header}:{}),...(body?{content:body,read_time_mins:Math.max(1,Math.ceil(body.trim().split(/\s+/).length/220))}:{}),...(photo?{header_image_url:photo}:{})});router.push("/studio/blogs")}catch(err){setError(err instanceof Error?err.message:"Could not update Ledger entry. You may not own this record.")}finally{setSaving(false)}};return <StudioShell title="Edit Ledger Entry" intro="Change only the parts you want to replace."><TacticalCard><form onSubmit={submit} className="grid gap-6"><label className="grid gap-2 text-xs font-semibold uppercase tracking-[.18em] text-gold">New header<input className={field} value={header} onChange={e=>setHeader(e.target.value)}/></label><ImageUpload label="Replacement header photo" value={photo} onChange={setPhoto}/><label className="grid gap-2 text-xs font-semibold uppercase tracking-[.18em] text-gold">New body<textarea className={`${field} min-h-80 normal-case leading-7 tracking-normal`} placeholder="Leave blank to keep the current article body." value={body} onChange={e=>setBody(e.target.value)}/></label>{error&&<p className="text-red-200">{error}</p>}<button disabled={saving} className="bg-gold px-5 py-3 text-xs font-semibold uppercase tracking-[.2em] text-navy disabled:opacity-50">{saving?"Saving...":"Save changes"}</button></form></TacticalCard></StudioShell>}
