"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { createBlog } from "@/lib/api/blogs";
import { StudioShell } from "@/components/studio/StudioShell";
import { ImageUpload } from "@/components/studio/ImageUpload";
import { TacticalCard } from "@/components/ui/states";
const categories=["Game Theories","Games","State of the Art","Research","Studies","CS/DSA"],field="border border-gold/20 bg-ink p-3 text-white outline-none focus:border-gold/60";
export default function NewBlogPage(){const router=useRouter(),[error,setError]=useState<string|null>(null),[saving,setSaving]=useState(false),[form,setForm]=useState({title:"",category:"Game Theories",header_image_url:"",content:"",tags:"",status:"draft" as "draft"|"published"});const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError(null);try{const data=await createBlog({...form,tags:form.tags.split(",").map(x=>x.trim()).filter(Boolean),read_time_mins:Math.max(1,Math.ceil(form.content.trim().split(/\s+/).length/220))});router.push(`/studio/blogs/${data.blog._id}/edit`)}catch(err){setError(err instanceof Error?err.message:"Could not save Ledger entry")}finally{setSaving(false)}};return <StudioShell title="New Ledger Entry" intro="Add the headline, cover, and article body—reading time is calculated automatically."><TacticalCard><form onSubmit={submit} className="grid gap-6"><label className="grid gap-2 text-xs font-semibold uppercase tracking-[.18em] text-gold">Header<input required className={field} placeholder="The title readers will see" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><ImageUpload required label="Header photo" value={form.header_image_url} onChange={header_image_url=>setForm({...form,header_image_url})}/><label className="grid gap-2 text-xs font-semibold uppercase tracking-[.18em] text-gold">Body<textarea required className={`${field} min-h-80 normal-case leading-7 tracking-normal`} placeholder="Write the article here. Use blank lines to separate paragraphs." value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></label><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-xs uppercase tracking-[.18em] text-gold">Category<select className={field} value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label className="grid gap-2 text-xs uppercase tracking-[.18em] text-gold">Publishing<select className={field} value={form.status} onChange={e=>setForm({...form,status:e.target.value as "draft"|"published"})}><option value="draft">Save as draft</option><option value="published">Publish now</option></select></label></div><label className="grid gap-2 text-xs uppercase tracking-[.18em] text-gold">Tags <span className="normal-case tracking-normal text-white/40">Optional, separated by commas</span><input className={field} placeholder="economics, strategy, diplomacy" value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/></label>{error&&<p className="text-red-200">{error}</p>}<button disabled={saving} className="bg-gold px-5 py-3 text-xs font-semibold uppercase tracking-[.2em] text-navy disabled:opacity-50">{saving?"Saving...":"Save Ledger entry"}</button></form></TacticalCard></StudioShell>}
