"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { createGame } from "@/lib/api/games";
import { StudioShell } from "@/components/studio/StudioShell";
import { ImageUpload } from "@/components/studio/ImageUpload";
import { TacticalCard } from "@/components/ui/states";
const field="border border-gold/20 bg-ink p-3 text-white outline-none focus:border-gold/60";
export default function NewGamePage(){
 const router=useRouter(),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[form,setForm]=useState({name:"",tagline:"",description:"",game_type:"Zero-Sum",difficulty:"Beginner",play_url:"",thumbnail_url:"",tags:""});
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError(null);try{const data=await createGame({...form,tags:form.tags.split(",").map(x=>x.trim()).filter(Boolean)});router.push(`/studio/games/${data.game._id}/edit`)}catch(err){setError(err instanceof Error?err.message:"Could not save game")}finally{setSaving(false)}};
 return <StudioShell title="Add Game" intro="Create a visual experiment card for the Game Lab."><TacticalCard><form onSubmit={submit} className="grid gap-6"><label className="grid gap-2 text-xs uppercase tracking-[.18em] text-gold">Game name<input required className={field} placeholder="Prisoner's Dilemma" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="grid gap-2 text-xs uppercase tracking-[.18em] text-gold">Short tagline<input className={field} placeholder="One sentence shown on the card" value={form.tagline} onChange={e=>setForm({...form,tagline:e.target.value})}/></label><ImageUpload required label="Game cover photo" value={form.thumbnail_url} onChange={thumbnail_url=>setForm({...form,thumbnail_url})}/><label className="grid gap-2 text-xs uppercase tracking-[.18em] text-gold">Description<textarea required className={`${field} min-h-40 normal-case tracking-normal`} placeholder="Explain the game, its rules, and what members will learn." value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-xs uppercase tracking-[.18em] text-gold">Domain<select className={field} value={form.game_type} onChange={e=>setForm({...form,game_type:e.target.value})}>{["Zero-Sum","Cooperative","Auction","Coordination"].map(x=><option key={x}>{x}</option>)}</select></label><label className="grid gap-2 text-xs uppercase tracking-[.18em] text-gold">Difficulty<select className={field} value={form.difficulty} onChange={e=>setForm({...form,difficulty:e.target.value})}>{["Beginner","Intermediate","Advanced"].map(x=><option key={x}>{x}</option>)}</select></label></div><label className="grid gap-2 text-xs uppercase tracking-[.18em] text-gold">Play link <span className="normal-case tracking-normal text-white/40">Optional</span><input type="url" className={field} placeholder="https://..." value={form.play_url} onChange={e=>setForm({...form,play_url:e.target.value})}/></label><label className="grid gap-2 text-xs uppercase tracking-[.18em] text-gold">Tags<input className={field} placeholder="strategy, negotiation, multiplayer" value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/></label>{error&&<p className="text-red-200">{error}</p>}<button disabled={saving} className="bg-gold px-5 py-3 text-xs font-semibold uppercase tracking-[.2em] text-navy disabled:opacity-50">{saving?"Saving...":"Save game"}</button></form></TacticalCard></StudioShell>;
}
